t=(20,38,67,54,90,88,38)
print("Tuple is:",t)
print("The first element is :",t[0])
print("The last element is :",t[-1])
print("Length:",len(t))
print("Count of 38:",t.count(38))
print("Index of 90:",t.index(90))
print("IS 70 present?",70 in t)
print("Maximum:",max(t))
print("Minimum:",min(t))
print("Sum:",sum(t))
l=list(t)
print("Converted to list:",l)
t=tuple(l)
print("Converted to tuple:",t)

